# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Badge Conditionned Permission

# Model Form Field configuration
form: $/sunlab/gamificationpermissions/models/badgeconditionnedpermission/fields.yaml

# Model Class name
modelClass: SunLab\GamificationPermissions\Models\BadgeConditionnedPermission

# Default redirect location
defaultRedirect: sunlab/gamificationpermissions/badgeconditionnedpermissions

# Create page
create:
    title: backend::lang.form.create_title
    redirect: sunlab/gamificationpermissions/badgeconditionnedpermissions/update/:id
    redirectClose: sunlab/gamificationpermissions/badgeconditionnedpermissions

# Update page
update:
    title: backend::lang.form.update_title
    redirect: sunlab/gamificationpermissions/badgeconditionnedpermissions
    redirectClose: sunlab/gamificationpermissions/badgeconditionnedpermissions

# Preview page
preview:
    title: backend::lang.form.preview_title
